services:

  smart-admin-web:
    image: nginx
    hostname: smart-admin-web
    container_name: smart-admin-web
    user: root
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
    extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - 8082:80
    volumes:
      - ./smart-admin-web:/etc/nginx/html:ro

  smart-admin-kotlin:
    image: open-liberty:22.0.0.9-full-java17-openj9
    hostname: smart-admin-kotlin
    container_name: smart-admin-kotlin
    user: root
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS='-Xms128m -Xmx1024m'
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1g
    extra_hosts:
        - "host.docker.internal:host-gateway"
        - "redis:host-gateway"
        - "postgresql:host-gateway"
    ports:
      - "1024:1024"
    working_dir: /usr/jar
    command: /bin/bash -c "java -jar smart-admin-kotlin.jar $${JAVA_OPTS}"
    volumes:
      - ./smart-admin-kotlin.jar:/usr/jar/smart-admin-kotlin.jar:ro